# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: aellxx.dev
email: bluebayband@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal notes and neural thoughts on my journey learning AI/ML + more — backpropagating insights as I go.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aellxx.dev" 
linkedin_username: aellee
github_username:  aellxx

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# Collection for categories
collections:
  category:
    output: true

# Include additional directories if needed
include:
  - _includes
  - _layouts
  - _pages

# Giscus Comments Configuration
giscus:
  data-repo: "aellxx/aellxx.github.io"
  data-repo-id: "R_kgDOOZDNQg"
  data-category: "Blog Comments" 
  data-category-id: "DIC_kwDOOZDNQs4CpIdh"
  data-theme: "light"
  enabled: true

plugins:
  - jekyll-feed